[package]
name = "TestPkg"
version = "0.0.0"

[addresses]
A = "0xCAFE"

[dependencies]
MoveStdlib = { git = "https://github.com/diem/move.git", subdir = "language/move-stdlib", addr_subst = { "Std" = "0x1" }, rev = "98ed299" }
