[package]
name = "TestPkg"
version = "0.0.0"

[addresses]
A = "0xCAFE"

[dependencies]
MoveStdlib = { git = "https://github.com/diem/diem.git", subdir = "language/move-stdlib", addr_subst = { "Std" = "0x1" }, rev = "96d28e132dac33542bdafa4ac25324015d083bf1" }
